"use client";

import { useDescope, useSession, useUser } from "@descope/nextjs-sdk/client";
import Head from "next/head";
import Link from "next/link";
import { SyntheticEvent, useCallback, useState } from "react";
import styles from "../styles/Home.module.css";
import { trpc_api } from '../app/utils/trpc';
import { AuthProvider } from '@descope/nextjs-sdk';

const getUserDisplayName = (user: any) =>
  user?.name || user?.externalIds?.[0] || "";

export default trpc_api.withTRPC(function Home() {
    
  const { isAuthenticated } = useSession();
  const { user } = useUser();
  const { logout } = useDescope();

  const onLogout = useCallback(() => {
    logout();
  }, [logout]);

  const [apiFormResult, setApiFormResult] = useState<string>("");
  const [value, setValue] = useState();

  // response should hold off and then refresh when isAuthenticated = true
  const response = trpc_api.hello.useQuery({enabled: isAuthenticated});

  const handleSubmit = async (event: SyntheticEvent) => {
    event.preventDefault();
    const resultMessage = `Result: ${response.data}`;
    setApiFormResult(resultMessage);
    alert(resultMessage);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the{" "}
          <a href="https://github.com/descope-sample-apps/next-js-sample-app">
            Descope Next.js Sample App
          </a>
        </h1>
        {!isAuthenticated && (
            
          <Link href="/login" passHref>
            <div>{`Authenticated: ${isAuthenticated}`}</div>
            <div>{`Response: ${response.data}`}</div>
            <button>Login</button>
          </Link>
        )}
        {isAuthenticated && (
          <>
            <div className={styles.description}>
              Hello {getUserDisplayName(user)}
            </div>
            <div>{`Authenticated: ${isAuthenticated}`}</div>
            <div>{`Result: ${response.data}`}</div>
            <button onClick={onLogout}>Logout</button>
            <div className={styles.description}>Submit TRPC Form</div>
            <form onSubmit={handleSubmit}>
              <button data-cy="api-form-button" type="submit">
                Submit
              </button>
            </form>
            <div>{apiFormResult}</div>
          </>
        )}

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>app/page.tsx</code>
        </p>
      </main>
    </div>
  );
});